language: objective-c
osx_image: xcode6.4
notifications:
  email: false
node_js:
  - "0.12"
env:
  global:
    - _FORCE_LOGS=1
  matrix:
    - CI_CONFIG=unit
    - CI_CONFIG=functional
install:
  - node --version
  - npm install
  - npm install -g gulp jshint
script:
  - gulp eslint
  - make travis
after_success:
  - gulp coveralls
